using System;
using System.Collections.Generic;
using System.Linq;
using YoutubeDLSharp.Metadata;

namespace VideoTranslator.Services;

public static class VideoDataExtensions
{
    #region VideoData 扩展方法

    public static string GetFormattedDuration(this VideoData videoData)
    {
        if (!videoData.Duration.HasValue)
            return string.Empty;
        return TimeSpan.FromSeconds(videoData.Duration.Value).ToString(@"hh\:mm\:ss");
    }

    public static string GetFormattedViewCount(this VideoData videoData)
    {
        return videoData.ViewCount?.ToString() ?? string.Empty;
    }

    public static string GetFormattedLikeCount(this VideoData videoData)
    {
        return videoData.LikeCount?.ToString() ?? string.Empty;
    }

    public static string GetFormattedUploadDate(this VideoData videoData)
    {
        return videoData.UploadDate?.ToString("yyyyMMdd") ?? string.Empty;
    }

    public static string GetFormattedAverageRating(this VideoData videoData)
    {
        return videoData.AverageRating?.ToString("F2") ?? string.Empty;
    }

    public static List<FormatData> GetVideoFormats(this VideoData videoData)
    {
        if (videoData.Formats == null)
            return new List<FormatData>();

        return videoData.Formats
            .Where(f => f != null && 
                       !string.IsNullOrEmpty(f.VideoCodec) && 
                       f.VideoCodec != "none" && 
                       f.VideoCodec != "audio only")
            .ToList();
    }

    public static List<FormatData> GetAudioFormats(this VideoData videoData)
    {
        if (videoData.Formats == null)
            return new List<FormatData>();

        return videoData.Formats
            .Where(f => f != null && 
                       f.VideoCodec == "none" && 
                       f.VideoCodec != "audio only" &&
                       f.Resolution == "audio only")
            .ToList();
    }

    public static List<SubtitleInfo> GetSubtitleInfos(this VideoData videoData)
    {
        var result = new List<SubtitleInfo>();

        if (videoData.Subtitles != null)
        {
            foreach (var subtitlePair in videoData.Subtitles)
            {
                result.Add(new SubtitleInfo
                {
                    LanguageCode = subtitlePair.Key,
                    LanguageName = GetLanguageName(subtitlePair.Key),
                    IsAutoGenerated = false
                });
            }
        }

        if (videoData.AutomaticCaptions != null)
        {
            foreach (var subtitlePair in videoData.AutomaticCaptions)
            {
                if (!result.Any(s => s.LanguageCode == subtitlePair.Key))
                {
                    result.Add(new SubtitleInfo
                    {
                        LanguageCode = subtitlePair.Key,
                        LanguageName = GetLanguageName(subtitlePair.Key),
                        IsAutoGenerated = true
                    });
                }
            }
        }

        return result;
    }

    #endregion

    #region FormatData 扩展方法

    public static string GetFormattedFileSize(this FormatData formatData)
    {
        var bytes = formatData.FileSize ?? formatData.ApproximateFileSize ?? 0;
        return FormatFileSize(bytes);
    }

    public static long GetFileSizeBytes(this FormatData formatData)
    {
        return formatData.FileSize ?? formatData.ApproximateFileSize ?? 0;
    }

    public static string GetFormattedFps(this FormatData formatData)
    {
        return formatData.FrameRate?.ToString("F0") ?? string.Empty;
    }

    public static string GetFormattedTbr(this FormatData formatData)
    {
        return formatData.Bitrate?.ToString("F2") ?? string.Empty;
    }

    public static string GetFormattedVbr(this FormatData formatData)
    {
        return formatData.VideoBitrate?.ToString("F2") ?? string.Empty;
    }

    public static string GetFormattedAbr(this FormatData formatData)
    {
        return formatData.AudioBitrate?.ToString("F2") ?? string.Empty;
    }

    public static bool RequiresPremium(this FormatData formatData)
    {
        if (!string.IsNullOrEmpty(formatData.FormatNote) && formatData.FormatNote.Contains("premium", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (!string.IsNullOrEmpty(formatData.Resolution))
        {
            if (formatData.Resolution.Contains("4K", StringComparison.OrdinalIgnoreCase) ||
                formatData.Resolution.Contains("2160p", StringComparison.OrdinalIgnoreCase) ||
                formatData.Resolution.Contains("1440p", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    #endregion

    #region 辅助方法

    private static string FormatFileSize(long bytes)
    {
        if (bytes == 0)
            return "0 B";

        string[] sizes = { "B", "KB", "MB", "GB", "TB" };
        int order = 0;
        double size = bytes;

        while (size >= 1024 && order < sizes.Length - 1)
        {
            order++;
            size /= 1024;
        }

        return $"{size:0.##} {sizes[order]}";
    }

    private static string GetLanguageName(string languageCode)
    {
        var languageMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "en", "English" },
            { "zh", "Chinese" },
            { "zh-Hans", "Chinese (Simplified)" },
            { "zh-Hant", "Chinese (Traditional)" },
            { "ja", "Japanese" },
            { "ko", "Korean" },
            { "es", "Spanish" },
            { "fr", "French" },
            { "de", "German" },
            { "ru", "Russian" },
            { "pt", "Portuguese" },
            { "it", "Italian" },
            { "ar", "Arabic" },
            { "hi", "Hindi" },
            { "th", "Thai" },
            { "vi", "Vietnamese" },
            { "id", "Indonesian" },
            { "ms", "Malay" },
            { "tr", "Turkish" },
            { "pl", "Polish" },
            { "nl", "Dutch" },
            { "sv", "Swedish" },
            { "da", "Danish" },
            { "no", "Norwegian" },
            { "fi", "Finnish" },
            { "uk", "Ukrainian" },
            { "cs", "Czech" },
            { "ro", "Romanian" },
            { "hu", "Hungarian" },
            { "el", "Greek" },
            { "he", "Hebrew" },
            { "bn", "Bengali" },
            { "ta", "Tamil" },
            { "te", "Telugu" },
            { "mr", "Marathi" },
            { "ur", "Urdu" }
        };

        return languageMap.TryGetValue(languageCode, out var name) ? name : languageCode;
    }

    #endregion
}

#region 辅助类型

public class SubtitleInfo
{
    public string LanguageCode { get; set; } = string.Empty;
    public string LanguageName { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
}

#endregion
