namespace VideoTranslator.Models;

public class YouTubeVideo
{
    public string VideoId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Url { get; set; } = string.Empty;
    public string? ThumbnailUrl { get; set; }
    public TimeSpan Duration { get; set; }
    public string? Description { get; set; }
    public string? Uploader { get; set; }
    public DateTime? UploadDate { get; set; }
    public int DurationSeconds { get; set; }
    public string DurationText { get; set; } = string.Empty;
    public long ViewCount { get; set; }
    public long LikeCount { get; set; }
    public long CommentCount { get; set; }
    public string? Tags { get; set; }
    public string? Category { get; set; }
    public int AgeLimit { get; set; }
    public bool IsLive { get; set; }
    public bool Is4K { get; set; }
    public string? Resolution { get; set; }
    public string? Format { get; set; }
    public long FileSize { get; set; }
    public string FileSizeText { get; set; } = string.Empty;
    public List<YouTubeSubtitle> AvailableSubtitles { get; set; } = new();
    public List<YouTubeAudio> AvailableAudios { get; set; } = new();
    public List<YouTubeVideoStream> AvailableVideos { get; set; } = new();
}

public class YouTubeSubtitle
{
    public string LanguageCode { get; set; } = string.Empty;
    public string LanguageName { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
    public string? DownloadUrl { get; set; }
}

public class YouTubeAudio
{
    public string FormatId { get; set; } = string.Empty;
    public string Extension { get; set; } = string.Empty;
    public string Quality { get; set; } = string.Empty;
    public int Bitrate { get; set; }
    public long FileSize { get; set; }
    public string? DownloadUrl { get; set; }
}
